In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(r'/content/heart.csv')

find total row count

In [ ]:
df.shape[0]

1025

each target column count

In [ ]:
df.groupby('target')['target'].count()

target
0    499
1    526
Name: target, dtype: int64

separate x and y

In [ ]:
y=df.iloc[:,-1]
x=df.iloc[:,:-1]
print(y)
print(x)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0     125.0   212    0      NaN    168.0      0      1.0
1      53    1   0     140.0   203    1      0.0    155.0      1      3.1
2      70    1   0     145.0   174    0      1.0    125.0      1      2.6
3      61    1   0     148.0   203    0      1.0      NaN      0      0.0
4      62    0   0     138.0   294    1      1.0    106.0      0      1.9
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4

      slope   ca  thal
0         2  2.0   3.0
1         0  0.0   3.0
2         0  0.0   3.0
3         2  1.0   3.0
4         1  3.0   2.0
...     ...  ...   ...
1020      2  0.0   2.0
1021      1  1.0   3.0
1022      1  1.0   2.0
1023      2  0.0   2.0
1024      1  1.0   3.0

[1025 rows x 13 columns]

display datatypes

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object


find total nu of missing alues

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

fill the missing value proper way

In [ ]:
x=df['trestbps'].mode()[0]
df['trestbps'].fillna(x,inplace=True)

/tmp/ipykernel_5048/290927382.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['trestbps'].fillna(x,inplace=True)

In [ ]:
x=df['restecg'].mode()[0]
df['restecg'].fillna(x,inplace=True)

/tmp/ipykernel_5048/1938559969.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['restecg'].fillna(x,inplace=True)

In [ ]:
x=df['thalach'].mean()
df['thalach'].fillna(x,inplace=True)

/tmp/ipykernel_5048/1947547177.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['thalach'].fillna(x,inplace=True)

In [ ]:
x=df['ca'].mode()[0]
df['ca'].fillna(x,inplace=True)
df.head(10)

/tmp/ipykernel_5048/589558053.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ca'].fillna(x,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1.0,168.000000,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.000000,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.000000,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,149.102539,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.000000,0,1.9,1,3.0,2.0,0
5,58,0,0,100.0,248,0,0.0,122.000000,0,1.0,1,0.0,2.0,1
6,58,1,0,114.0,318,0,2.0,140.000000,0,4.4,0,0.0,1.0,0
7,55,1,0,160.0,289,0,0.0,145.000000,1,0.8,1,1.0,3.0,0
8,46,1,0,120.0,249,0,0.0,144.000000,0,0.8,2,0.0,3.0,0
9,54,1,0,122.0,286,0,0.0,116.000000,1,3.2,1,2.0,2.0,0

In [ ]:
x=df['thal'].mode()[0]
df['thal'].fillna(x,inplace=True)
df.head(10)

/tmp/ipykernel_5048/3817911750.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['thal'].fillna(x,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1.0,168.000000,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.000000,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.000000,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,149.102539,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.000000,0,1.9,1,3.0,2.0,0
5,58,0,0,100.0,248,0,0.0,122.000000,0,1.0,1,0.0,2.0,1
6,58,1,0,114.0,318,0,2.0,140.000000,0,4.4,0,0.0,1.0,0
7,55,1,0,160.0,289,0,0.0,145.000000,1,0.8,1,1.0,3.0,0
8,46,1,0,120.0,249,0,0.0,144.000000,0,0.8,2,0.0,3.0,0
9,54,1,0,122.0,286,0,0.0,116.000000,1,3.2,1,2.0,2.0,0

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

thalach above 150 wrong data ====>mean fill

In [ ]:
x=df['thalach'].mean()
for i in df.index:
  if df.loc[i,'thalach'] > 150:
    df.loc[i,'thalach']=x

In [ ]:
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1.0,149.102539,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,149.102539,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.000000,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,149.102539,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.000000,0,1.9,1,3.0,2.0,0
5,58,0,0,100.0,248,0,0.0,122.000000,0,1.0,1,0.0,2.0,1
6,58,1,0,114.0,318,0,2.0,140.000000,0,4.4,0,0.0,1.0,0
7,55,1,0,160.0,289,0,0.0,145.000000,1,0.8,1,1.0,3.0,0
8,46,1,0,120.0,249,0,0.0,144.000000,0,0.8,2,0.0,3.0,0
9,54,1,0,122.0,286,0,0.0,116.000000,1,3.2,1,2.0,2.0,0